# Receiver Configuration
stego_settings:
  hamming_k: 3

input_output:
  stego_image_path: "data/stego_output.jpg"
  output_text_path: "data/decrypted_message.txt"

secret:
  password: "SuperSecretPassword123"